name: GitHub Actions Demo
on: [push]
jobs:
  git-clone:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step"
  npm-install:
    runs-on: ubuntu-latest
    needs: git-clone
    steps:
      - run: echo "Step"
  static-scan:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - run: echo "Step"
  lint:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - run: echo "Step"
  unit-tests:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - run: echo "Step"
  build:
    runs-on: ubuntu-latest
    needs: ['static-scan', 'lint', 'unit-tests']
    steps:
      - run: echo "Step"
  integration-tests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo "Step"
  performance-tests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo "Step"
  prepare-release:
      runs-on: ubuntu-latest
      needs: ['vulnerability-tests', 'license-check', 'integration-tests', 'owasp-tests']
      steps:
        - run: echo "Step"
  vulnerability-tests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo "Step"
  owasp-tests:
      runs-on: ubuntu-latest
      needs: vulnerability-tests
      steps:
        - run: echo "Step"
  license-check:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo "Step"
  cache-node-deps:
      runs-on: ubuntu-latest
      needs: npm-install
      steps:
        - run: echo "Step"
  deploy:
      runs-on: ubuntu-latest
      needs: 'prepare-release'
      steps:
        - run: echo "publish"
