name: GitHub Actions Demo
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step A"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Step B"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Step C"
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - run: echo "Step D"
