name: GitHub Actions Demo
on: [push]
jobs:
  git-clone:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Step A"
  npm-install:
    runs-on: ubuntu-latest
    needs: git-clone
    steps:
      - run: echo "Step B"
  static-scan:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - run: echo "Step C"
  lint:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - run: echo "Step D"
  unit-tests:
    runs-on: ubuntu-latest
    needs: npm-install
    steps:
      - run: echo "Step E"
  build:
    runs-on: ubuntu-latest
    needs: ['static-scan', 'lint', 'unit-tests']
    steps:
      - run: echo "Step F"
  integration-tests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo "Step G"
  publish:
      runs-on: ubuntu-latest
      needs: integration-tests
      steps:
        - run: echo "Step H"
